DESCRIPTION = "prop-mod-bd notranslate"
FACT_GROUPING = "disc-bullet"
INDIVIDUAL_FACT = "fact-bullet"
PROP_SUMMARY_CLASS = "prop-mod prop-summary "
ZILLOW_HOMES_URL = "http://zillow.com/homes/"
ZILLOW_URL = "http://zillow.com"
